### ISSUE TITLE
High CPU - macbook pro 2016 core i7

### ISSUE THREAD

**Issue by djjlewis** [marcdjulien/spotify-terminal#57]
It's great not to have to leave my terminal / tmux session yet still be able to control spotify, however I notice very high CPU (around 60%) reported from htop for spotify.py, even when no playback is occurring. 

This is on a 2016 macbook pro 2.9 GHz Intel Core i7 / 16GB ram, so I would not say it's under-spec'ed. Is anyone else seeing / reported this issue?

![image](https://user-images.githubusercontent.com/6518665/57813599-9add2880-7768-11e9-9191-43605f46ab15.png)

**Comment by marcdjulien** [comment]
Thanks for the info. I haven't done much characterization of performance of the application yet, but it's good to know that this is a potential problem. 

Is the high CPU usage sustained? Or does it just spike up every once in awhile?

**Comment by marcdjulien** [comment]
The CPU usage is correlated to the PROGRAM_LOOP:
https://github.com/marcdjulien/spotify-terminal/blob/master/display.py#L19

It's set to 0.1 by default. You can try bumping this up (e.g, 0.2) as a workaround until other optimizations are made.

**Comment by marcdjulien** [comment]
I made some updates. The program uses less CPU when it's idle (i.e, user isn't pressing any keys). It also uses less CPU after idle for 1 min. Let me know if it helps!
