### ISSUE TITLE
Unable to find devices

### ISSUE THREAD

**Issue by xcapaldi** [marcdjulien/spotify-terminal#76]
When trying to see the list of devices (W), the list is never able to load. I'm running this on a fairly minimal fedora system so maybe there are some unlisted dependencies. I haven't looked through the source yet.

**Comment by marcdjulien** [comment]
@xcapaldi make sure you have Spotify open on your device. If you're using the mobile version, you have to make sure it's open while selecting the device. If that still doesn't work, try playing a song through Spotify first.

**Comment by xcapaldi** [comment]
Okay, sorry, I misunderstood how this worked. It works perfectly for me with a Spotify web client running or Spotify on my phone. Thanks for the sweet package.
