### ISSUE TITLE
Searching for device issue

### ISSUE THREAD

**Issue by Neiwin** [marcdjulien/spotify-terminal#79]
I have issue with device searching.
When I startup the spotify client, everything works fine... It will load up and show my playlists, etc.
But when I hit play, the messege show up: No device is selected! Press W to open devices menu.
So I press W and new "window" pop up with searching with no response, it just freezes.

**Comment by marcdjulien** [comment]
@Neiwin Do you have Spotify running somewhere else? For example, on your phone or the desktop/web app? This program doesn't play music on its own, it just controls Spotify when it's already running elsewhere.

**Comment by marcdjulien** [comment]
@Neiwin did this work?

**Comment by jvlewis** [comment]
@marcdjulien Had the same problem and this guided me to some terminal tunes. Simple misunderstanding of how it worked. Thank you

**Comment by marcdjulien** [comment]
@jvlewis glad it's working! I will update the UI to make this more clear.

**Comment by marcdjulien** [comment]
I added a more help message in the search window in version 0.15.2. I hope this helps!
